package de.turing85.yane.impl.cpu6502;

import java.util.*;
import java.util.function.*;
import java.util.stream.*;
import lombok.*;

@Value
@EqualsAndHashCode
@AllArgsConstructor(access = AccessLevel.PRIVATE)
class Instruction implements de.turing85.yane.api.Instruction {
  static final Set<Instruction> INSTRUCTIONS;
  static final Map<Byte, Instruction> INSTRUCTIONS_BY_OPCODE;
  static final Map<String, Set<Instruction>> INSTRUCTIONS_BY_MNEMONIC;

  static {
    INSTRUCTIONS = Set.of(
        Instruction.of(Command.BRK, AddressMode.IMPLIED, (byte) 0x00,7),
        Instruction.of(Command.ORA, AddressMode.INDIRECT_ZERO_PAGE_X, (byte) 0x01,  2),
        Instruction.unknownInstruction((byte) 0x02),
        Instruction.unknownInstruction((byte) 0x03),
        Instruction.unknownInstruction((byte) 0x04),
        Instruction.of(Command.ORA, AddressMode.ZERO_PAGE, (byte) 0x05, 3),
        Instruction.of(Command.ASL, AddressMode.ZERO_PAGE, (byte) 0x06, 5),
        Instruction.unknownInstruction((byte) 0x07),
        Instruction.of(Command.PHP, AddressMode.IMPLIED, (byte) 0x08, 3),
        Instruction.of(Command.ORA, AddressMode.IMMEDIATE, (byte) 0x09, 2),
        Instruction.of(Command.ASL, AddressMode.ACCUMULATOR, (byte) 0x0A, 2),
        Instruction.unknownInstruction((byte) 0x0B),
        Instruction.unknownInstruction((byte) 0x0C),
        Instruction.of(Command.ORA, AddressMode.ABSOLUTE, (byte) 0x0D, 4),
        Instruction.of(Command.ASL, AddressMode.ABSOLUTE, (byte) 0x0E, 6),
        Instruction.unknownInstruction((byte) 0x0F),
        Instruction.of(Command.BPL, AddressMode.RELATIVE, (byte) 0x10, 2),
        Instruction.of(Command.ORA, AddressMode.INDIRECT_ZERO_PAGE_Y, (byte) 0x11, 5),
        Instruction.unknownInstruction((byte) 0x12),
        Instruction.unknownInstruction((byte) 0x13),
        Instruction.unknownInstruction((byte) 0x14),
        Instruction.of(Command.ORA, AddressMode.ZERO_PAGE_X, (byte) 0x15, 4),
        Instruction.of(Command.ASL, AddressMode.ZERO_PAGE_X, (byte) 0x16, 6),
        Instruction.unknownInstruction((byte) 0x17),
        Instruction.of(Command.CLC, AddressMode.IMPLIED, (byte) 0x18, 2),
        Instruction.of(Command.ORA, AddressMode.ABSOLUTE_Y, (byte) 0x19, 4),
        Instruction.unknownInstruction((byte) 0x1A),
        Instruction.unknownInstruction((byte) 0x1B),
        Instruction.unknownInstruction((byte) 0x1C),
        Instruction.of(Command.ORA, AddressMode.ABSOLUTE_X, (byte) 0x1D, 4),
        Instruction.of(Command.ASL, AddressMode.ABSOLUTE_X, (byte) 0x1E, 7),
        Instruction.unknownInstruction((byte) 0x1F),
        Instruction.of(Command.JSR, AddressMode.ABSOLUTE, (byte) 0x20, 6),
        Instruction.of(Command.AND, AddressMode.INDIRECT_ZERO_PAGE_X, (byte) 0x21, 6),
        Instruction.unknownInstruction((byte) 0x22),
        Instruction.unknownInstruction((byte) 0x23),
        Instruction.of(Command.BIT, AddressMode.ZERO_PAGE, (byte) 0x24, 3),
        Instruction.of(Command.AND, AddressMode.ZERO_PAGE, (byte) 0x25, 3),
        Instruction.of(Command.ROL, AddressMode.ZERO_PAGE, (byte) 0x26, 5),
        Instruction.unknownInstruction((byte) 0x27),
        Instruction.of(Command.PLP, AddressMode.IMPLIED, (byte) 0x28, 4),
        Instruction.of(Command.AND, AddressMode.IMMEDIATE, (byte) 0x29, 2),
        Instruction.of(Command.ROL, AddressMode.ACCUMULATOR, (byte) 0x2A, 2),
        Instruction.unknownInstruction((byte) 0x2B),
        Instruction.of(Command.BIT, AddressMode.ABSOLUTE, (byte) 0x2C, 4),
        Instruction.of(Command.AND, AddressMode.ABSOLUTE, (byte) 0x2D, 4),
        Instruction.of(Command.ROL, AddressMode.ABSOLUTE, (byte) 0x2E, 6),
        Instruction.unknownInstruction((byte) 0x2F),
        Instruction.of(Command.BMI, AddressMode.RELATIVE, (byte) 0x30, 2),
        Instruction.of(Command.AND, AddressMode.INDIRECT_ZERO_PAGE_Y, (byte) 0x31, 5),
        Instruction.unknownInstruction((byte) 0x32),
        Instruction.unknownInstruction((byte) 0x33),
        Instruction.unknownInstruction((byte) 0x34),
        Instruction.of(Command.AND, AddressMode.ZERO_PAGE_X, (byte) 0x35, 4),
        Instruction.of(Command.ROL, AddressMode.ZERO_PAGE_X, (byte) 0x36, 6),
        Instruction.unknownInstruction((byte) 0x37),
        Instruction.of(Command.SEC, AddressMode.IMPLIED, (byte) 0x38, 2),
        Instruction.of(Command.AND, AddressMode.ABSOLUTE_Y, (byte) 0x39, 4),
        Instruction.unknownInstruction((byte) 0x3A),
        Instruction.unknownInstruction((byte) 0x3B),
        Instruction.unknownInstruction((byte) 0x3C),
        Instruction.of(Command.AND, AddressMode.ABSOLUTE_X, (byte) 0x3D, 4),
        Instruction.of(Command.ROL, AddressMode.ABSOLUTE_X, (byte) 0x3E, 7),
        Instruction.unknownInstruction((byte) 0x3F),
        Instruction.of(Command.RTI, AddressMode.IMPLIED, (byte) 0x40, 6),
        Instruction.of(Command.EOR, AddressMode.INDIRECT_ZERO_PAGE_X, (byte) 0x41, 6),
        Instruction.unknownInstruction((byte) 0x42),
        Instruction.unknownInstruction((byte) 0x43),
        Instruction.unknownInstruction((byte) 0x44),
        Instruction.of(Command.EOR, AddressMode.ZERO_PAGE, (byte) 0x45, 3),
        Instruction.of(Command.LSR, AddressMode.ZERO_PAGE, (byte) 0x46, 5),
        Instruction.unknownInstruction((byte) 0x47),
        Instruction.of(Command.PHA, AddressMode.IMPLIED, (byte) 0x48, 3),
        Instruction.of(Command.EOR, AddressMode.IMMEDIATE, (byte) 0x49, 2),
        Instruction.of(Command.LSR, AddressMode.ACCUMULATOR, (byte) 0x4A, 2),
        Instruction.unknownInstruction((byte) 0x4B),
        Instruction.of(Command.JMP, AddressMode.ABSOLUTE, (byte) 0x4C, 3),
        Instruction.of(Command.EOR, AddressMode.ABSOLUTE, (byte) 0x4D, 4),
        Instruction.of(Command.LSR, AddressMode.ABSOLUTE, (byte) 0x4E, 6),
        Instruction.unknownInstruction((byte) 0x4F),
        Instruction.of(Command.BVC, AddressMode.RELATIVE, (byte) 0x50, 2),
        Instruction.of(Command.EOR, AddressMode.ZERO_PAGE_Y, (byte) 0x51, 5),
        Instruction.unknownInstruction((byte) 0x52),
        Instruction.unknownInstruction((byte) 0x53),
        Instruction.unknownInstruction((byte) 0x54),
        Instruction.of(Command.EOR, AddressMode.ZERO_PAGE_X, (byte) 0x55, 4),
        Instruction.of(Command.LSR, AddressMode.ZERO_PAGE_X, (byte) 0x56, 6),
        Instruction.unknownInstruction((byte) 0x57),
        Instruction.of(Command.CLI, AddressMode.IMPLIED, (byte) 0x58, 2),
        Instruction.of(Command.EOR, AddressMode.ABSOLUTE_Y, (byte) 0x59, 4),
        Instruction.unknownInstruction((byte) 0x5A),
        Instruction.unknownInstruction((byte) 0x5B),
        Instruction.unknownInstruction((byte) 0x5C),
        Instruction.of(Command.EOR, AddressMode.ABSOLUTE_X, (byte) 0x5D, 4),
        Instruction.of(Command.LSR, AddressMode.ABSOLUTE_X, (byte) 0x5E, 7),
        Instruction.unknownInstruction((byte) 0x5F),
        Instruction.of(Command.RTS, AddressMode.IMPLIED, (byte) 0x60, 6),
        Instruction.of(Command.ADC, AddressMode.INDIRECT_ZERO_PAGE_X, (byte) 0x61, 6),
        Instruction.unknownInstruction((byte) 0x62),
        Instruction.unknownInstruction((byte) 0x63),
        Instruction.unknownInstruction((byte) 0x64),
        Instruction.of(Command.ADC, AddressMode.ZERO_PAGE, (byte) 0x65, 3),
        Instruction.of(Command.ROR, AddressMode.ZERO_PAGE, (byte) 0x66, 5),
        Instruction.unknownInstruction((byte) 0x67),
        Instruction.of(Command.PLA, AddressMode.IMPLIED, (byte) 0x68, 4),
        Instruction.of(Command.ADC, AddressMode.IMMEDIATE, (byte) 0x69, 2),
        Instruction.of(Command.ROR, AddressMode.ACCUMULATOR, (byte) 0x6A, 2),
        Instruction.unknownInstruction((byte) 0x6B),
        Instruction.of(Command.JMP, AddressMode.INDIRECT, (byte) 0x6C, 5),
        Instruction.of(Command.ADC, AddressMode.ABSOLUTE, (byte) 0x6D, 4),
        Instruction.of(Command.ROR, AddressMode.ABSOLUTE, (byte) 0x6E, 6),
        Instruction.unknownInstruction((byte) 0x6F),
        Instruction.of(Command.BVS, AddressMode.RELATIVE, (byte) 0x70, 2),
        Instruction.of(Command.ADC, AddressMode.INDIRECT_ZERO_PAGE_Y, (byte) 0x71, 5),
        Instruction.unknownInstruction((byte) 0x72),
        Instruction.unknownInstruction((byte) 0x73),
        Instruction.unknownInstruction((byte) 0x74),
        Instruction.of(Command.ADC, AddressMode.ZERO_PAGE_X, (byte) 0x75, 4),
        Instruction.of(Command.ROR, AddressMode.ZERO_PAGE_X, (byte) 0x76, 6),
        Instruction.unknownInstruction((byte) 0x77),
        Instruction.of(Command.SEI, AddressMode.IMPLIED, (byte) 0x78, 2),
        Instruction.of(Command.ADC, AddressMode.ABSOLUTE_Y, (byte) 0x79, 4),
        Instruction.unknownInstruction((byte) 0x7A),
        Instruction.unknownInstruction((byte) 0x7B),
        Instruction.unknownInstruction((byte) 0x7C),
        Instruction.of(Command.ADC, AddressMode.ABSOLUTE_X, (byte) 0x7D, 4),
        Instruction.of(Command.ROR, AddressMode.ABSOLUTE_X, (byte) 0x7E, 7),
        Instruction.unknownInstruction((byte) 0x7F),
        Instruction.unknownInstruction((byte) 0x80),
        Instruction.of(Command.STA, AddressMode.INDIRECT_ZERO_PAGE_X, (byte) 0x81, 6),
        Instruction.unknownInstruction((byte) 0x82),
        Instruction.unknownInstruction((byte) 0x83),
        Instruction.of(Command.STY, AddressMode.ZERO_PAGE, (byte) 0x84, 3),
        Instruction.of(Command.STA, AddressMode.ZERO_PAGE, (byte) 0x85, 3),
        Instruction.of(Command.STX, AddressMode.ZERO_PAGE, (byte) 0x86, 3),
        Instruction.unknownInstruction((byte) 0x87),
        Instruction.of(Command.DEY, AddressMode.IMPLIED, (byte) 0x88, 2),
        Instruction.unknownInstruction((byte) 0x89),
        Instruction.of(Command.TXA, AddressMode.IMPLIED, (byte) 0x8A, 2),
        Instruction.unknownInstruction((byte) 0x8B),
        Instruction.of(Command.STY, AddressMode.ABSOLUTE, (byte) 0x8C, 4),
        Instruction.of(Command.STA, AddressMode.ABSOLUTE, (byte) 0x8D, 4),
        Instruction.of(Command.STX, AddressMode.ABSOLUTE, (byte) 0x8E, 4),
        Instruction.unknownInstruction((byte) 0x8F),
        Instruction.of(Command.BCC, AddressMode.RELATIVE, (byte) 0x90, 2),
        Instruction.of(Command.STA, AddressMode.INDIRECT_ZERO_PAGE_Y, (byte) 0x91, 6),
        Instruction.unknownInstruction((byte) 0x92),
        Instruction.unknownInstruction((byte) 0x93),
        Instruction.of(Command.STY, AddressMode.ZERO_PAGE_X, (byte) 0x94, 4),
        Instruction.of(Command.STA, AddressMode.ZERO_PAGE_X, (byte) 0x95, 4),
        Instruction.of(Command.STX, AddressMode.ZERO_PAGE_Y, (byte) 0x96, 4),
        Instruction.unknownInstruction((byte) 0x97),
        Instruction.of(Command.TYA, AddressMode.IMPLIED, (byte) 0x98, 2),
        Instruction.of(Command.STA, AddressMode.ABSOLUTE_Y, (byte) 0x99, 5),
        Instruction.of(Command.TXS, AddressMode.IMPLIED, (byte) 0x9A, 2),
        Instruction.unknownInstruction((byte) 0x9B),
        Instruction.unknownInstruction((byte) 0x9C),
        Instruction.of(Command.STA, AddressMode.ABSOLUTE_X, (byte) 0x9D, 5),
        Instruction.unknownInstruction((byte) 0x9E),
        Instruction.unknownInstruction((byte) 0x9F),
        Instruction.of(Command.LDY, AddressMode.IMMEDIATE, (byte) 0xA0, 2),
        Instruction.of(Command.LDA, AddressMode.INDIRECT_ZERO_PAGE_X, (byte) 0xA1, 6),
        Instruction.of(Command.LDX, AddressMode.IMMEDIATE, (byte) 0xA2, 2),
        Instruction.unknownInstruction((byte) 0xA3),
        Instruction.of(Command.LDY, AddressMode.ZERO_PAGE, (byte) 0xA4, 3),
        Instruction.of(Command.LDA, AddressMode.ZERO_PAGE, (byte) 0xA5, 3),
        Instruction.of(Command.LDX, AddressMode.ZERO_PAGE, (byte) 0xA6, 3),
        Instruction.unknownInstruction((byte) 0xA7),
        Instruction.of(Command.TAY, AddressMode.IMPLIED, (byte) 0xA8, 2),
        Instruction.of(Command.LDA, AddressMode.IMMEDIATE, (byte) 0xA9, 2),
        Instruction.of(Command.TAX, AddressMode.IMPLIED, (byte) 0xAA, 2),
        Instruction.unknownInstruction((byte) 0xAB),
        Instruction.of(Command.LDY, AddressMode.ABSOLUTE, (byte) 0xAC, 4),
        Instruction.of(Command.LDA, AddressMode.ABSOLUTE, (byte) 0xAD, 4),
        Instruction.of(Command.LDX, AddressMode.ABSOLUTE, (byte) 0xAE, 4),
        Instruction.unknownInstruction((byte) 0xAF),
        Instruction.of(Command.BCS, AddressMode.RELATIVE, (byte) 0xB0, 2),
        Instruction.of(Command.LDA, AddressMode.INDIRECT_ZERO_PAGE_Y, (byte) 0xB1, 5),
        Instruction.unknownInstruction((byte) 0xB2),
        Instruction.unknownInstruction((byte) 0xB3),
        Instruction.of(Command.LDY, AddressMode.ZERO_PAGE_X, (byte) 0xB4, 4),
        Instruction.of(Command.LDA, AddressMode.ZERO_PAGE_X, (byte) 0xB5, 4),
        Instruction.of(Command.LDX, AddressMode.ZERO_PAGE_Y, (byte) 0xB6, 4),
        Instruction.unknownInstruction((byte) 0xB7),
        Instruction.of(Command.CLV, AddressMode.IMPLIED, (byte) 0xB8, 2),
        Instruction.of(Command.LDA, AddressMode.ABSOLUTE_Y, (byte) 0xB9, 4),
        Instruction.of(Command.TSX, AddressMode.IMPLIED, (byte) 0xBA, 2),
        Instruction.unknownInstruction((byte) 0xBB),
        Instruction.of(Command.LDY, AddressMode.ABSOLUTE_X, (byte) 0xBC, 4),
        Instruction.of(Command.LDA, AddressMode.ABSOLUTE_X, (byte) 0xBD, 4),
        Instruction.of(Command.LDX, AddressMode.ABSOLUTE_Y, (byte) 0xBE, 4),
        Instruction.unknownInstruction((byte) 0xBF),
        Instruction.of(Command.CPY, AddressMode.IMMEDIATE, (byte) 0xC0, 2),
        Instruction.of(Command.CMP, AddressMode.INDIRECT_ZERO_PAGE_X, (byte) 0xC1, 6),
        Instruction.unknownInstruction((byte) 0xC2),
        Instruction.unknownInstruction((byte) 0xC3),
        Instruction.of(Command.CPY, AddressMode.ZERO_PAGE, (byte) 0xC4, 3),
        Instruction.of(Command.CMP, AddressMode.ZERO_PAGE, (byte) 0xC5, 3),
        Instruction.of(Command.DEC, AddressMode.ZERO_PAGE, (byte) 0xC6, 5),
        Instruction.unknownInstruction((byte) 0xC7),
        Instruction.of(Command.INY, AddressMode.IMPLIED, (byte) 0xC8, 2),
        Instruction.of(Command.CMP, AddressMode.IMMEDIATE, (byte) 0xC9, 2),
        Instruction.of(Command.DEX, AddressMode.IMPLIED, (byte) 0xCA, 2),
        Instruction.unknownInstruction((byte) 0xCB),
        Instruction.of(Command.CPY, AddressMode.ABSOLUTE, (byte) 0xCC, 4),
        Instruction.of(Command.CMP, AddressMode.ABSOLUTE, (byte) 0xCD, 4),
        Instruction.of(Command.DEC, AddressMode.ABSOLUTE, (byte) 0xCE, 6),
        Instruction.unknownInstruction((byte) 0xCF),
        Instruction.of(Command.BNE, AddressMode.RELATIVE, (byte) 0xD0, 2),
        Instruction.of(Command.CMP, AddressMode.INDIRECT_ZERO_PAGE_Y, (byte) 0xD1, 5),
        Instruction.unknownInstruction((byte) 0xD2),
        Instruction.unknownInstruction((byte) 0xD3),
        Instruction.unknownInstruction((byte) 0xD4),
        Instruction.of(Command.CMP, AddressMode.ZERO_PAGE_X, (byte) 0xD5, 4),
        Instruction.of(Command.DEC, AddressMode.ZERO_PAGE_X, (byte) 0xD6, 6),
        Instruction.unknownInstruction((byte) 0xD7),
        Instruction.of(Command.CLD, AddressMode.IMPLIED, (byte) 0xD8, 2),
        Instruction.of(Command.CMP, AddressMode.ABSOLUTE_Y, (byte) 0xD9, 4),
        Instruction.unknownInstruction((byte) 0xDA),
        Instruction.unknownInstruction((byte) 0xDB),
        Instruction.unknownInstruction((byte) 0xDC),
        Instruction.of(Command.CMP, AddressMode.ABSOLUTE_X, (byte) 0xDD, 4),
        Instruction.of(Command.DEC, AddressMode.ABSOLUTE_X, (byte) 0xDE, 7),
        Instruction.unknownInstruction((byte) 0xDF),
        Instruction.of(Command.CPX, AddressMode.IMMEDIATE, (byte) 0xE0, 2),
        Instruction.of(Command.SBC, AddressMode.INDIRECT_ZERO_PAGE_X, (byte) 0xE1, 6),
        Instruction.unknownInstruction((byte) 0xE2),
        Instruction.unknownInstruction((byte) 0xE3),
        Instruction.of(Command.CPX, AddressMode.ZERO_PAGE, (byte) 0xE4, 3),
        Instruction.of(Command.SBC, AddressMode.ZERO_PAGE, (byte) 0xE5, 3),
        Instruction.of(Command.INC, AddressMode.ZERO_PAGE, (byte) 0xE6, 5),
        Instruction.unknownInstruction((byte) 0xE7),
        Instruction.of(Command.INX, AddressMode.IMPLIED, (byte) 0xE8, 2),
        Instruction.of(Command.SBC, AddressMode.IMMEDIATE, (byte) 0xE9, 2),
        Instruction.of(Command.NOP, AddressMode.IMPLIED, (byte) 0xEA, 2),
        Instruction.unknownInstruction((byte) 0xEB),
        Instruction.of(Command.CPX, AddressMode.ABSOLUTE, (byte) 0xEC, 4),
        Instruction.of(Command.SBC, AddressMode.ABSOLUTE, (byte) 0xED, 4),
        Instruction.of(Command.INC, AddressMode.ABSOLUTE, (byte) 0xEE, 6),
        Instruction.unknownInstruction((byte) 0xEF),
        Instruction.of(Command.BEQ, AddressMode.RELATIVE, (byte) 0xF0, 2),
        Instruction.of(Command.SBC, AddressMode.INDIRECT_ZERO_PAGE_Y, (byte) 0xF1, 5),
        Instruction.unknownInstruction((byte) 0xF2),
        Instruction.unknownInstruction((byte) 0xF3),
        Instruction.unknownInstruction((byte) 0xF4),
        Instruction.of(Command.SBC, AddressMode.ZERO_PAGE_X, (byte) 0xF5, 4),
        Instruction.of(Command.INC, AddressMode.ZERO_PAGE_X, (byte) 0xF6, 6),
        Instruction.unknownInstruction((byte) 0xF7),
        Instruction.of(Command.SED, AddressMode.IMPLIED, (byte) 0xF8, 2),
        Instruction.of(Command.SBC, AddressMode.ABSOLUTE_Y, (byte) 0xF9, 4),
        Instruction.unknownInstruction((byte) 0xFA),
        Instruction.unknownInstruction((byte) 0xFB),
        Instruction.unknownInstruction((byte) 0xFC),
        Instruction.of(Command.SBC, AddressMode.ABSOLUTE_X, (byte) 0xFD, 4),
        Instruction.of(Command.INC, AddressMode.ABSOLUTE_X, (byte) 0xFE, 7),
        Instruction.unknownInstruction((byte) 0xFF));
    INSTRUCTIONS_BY_OPCODE = INSTRUCTIONS.stream()
        .collect(Collectors.toMap(
            Instruction::code,
            Function.identity()));
    INSTRUCTIONS_BY_MNEMONIC = INSTRUCTIONS.stream()
        .collect(Collectors.toMap(
            Instruction::mnemonic,
            Set::of,
            (lhs, rhs) -> Stream.concat(lhs.stream(), rhs.stream()).collect(Collectors.toSet())));
  }

  Command command;
  AddressMode addressMode;
  byte code;
  int cycles;

  public int bytesToRead() {
    return 1 + addressMode().bytesToRead();
  }

  private static Instruction of(
      Command command,
      AddressMode addressMode,
      byte code,
      int cycles) {
    return new Instruction(command, addressMode, code, cycles);
  }

  private static Instruction unknownInstruction(byte code) {
    return Instruction.of(Command.UNKNOWN, AddressMode.UNKNOWN, code, 1);
  }

  public String mnemonic() {
    return "%s %s".formatted(command().mnemonic(), addressMode().mnemonic());
  }

  @Override public String toString() {
    return "[0x%08X] \"%s\"".formatted(code(), mnemonic());
  }
}